version: '3'
services:
  server:
    build:
      context: ./google-sheets-api  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"  
    env_file:
      - .env  
    networks:
      - my-network
    restart: unless-stopped 
  client:
    build:
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "8065:80"  
    networks:
      - my-network
    depends_on:
      - server  
    restart: unless-stopped  #

networks:
  my-network:
    driver: bridge
