[build]
  command = "npm run build"  # Only one "command" allowed here
  publish = "public"         # React/Vite build output folder
  functions = "google-sheets-api"  # Serverless functions directory

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # Redirect to Netlify Functions
  status = 200

# Environment variables (set via Netlify UI instead!)
[build.environment]
  NODE_VERSION = "18"  # Example Node.js version