# netlify.toml
[build]
  # Define o diretório de construção da aplicação React
  command = "npm run build" # Ou seu comando de build
  functions = "google-sheets-api"   # Pasta onde as funções serverless estão
  publish = "public"        # Pasta de arquivos estáticos (se aplicável)
  
  # Define o comando para a construção da aplicação React
  command = "npm run build"

[[redirects]]
  # Redireciona requisições para o backend (API Node.js)
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
  force = true

[env]
  # Defina suas variáveis de ambiente aqui
  GOOGLE_TYPE = "your_google_type"
  GOOGLE_PROJECT_ID = "your_google_project_id"
  GOOGLE_PRIVATE_KEY_ID = "your_google_private_key_id"
  GOOGLE_PRIVATE_KEY = "your_google_private_key"
  GOOGLE_CLIENT_EMAIL = "your_google_client_email"
  GOOGLE_CLIENT_ID = "your_google_client_id"
  GOOGLE_AUTH_URI = "your_google_auth_uri"
  GOOGLE_TOKEN_URI = "your_google_token_uri"
  GOOGLE_AUTH_PROVIDER_CERT_URL = "your_google_auth_provider_cert_url"
  GOOGLE_CLIENT_CERT_URL = "your_google_client_cert_url"
  SHEET_ID = "your_google_sheet_id"
