[build]
  command = "npm install && npm run build" # Explicitly install dependencies first
  publish = "public"
  functions = "google-sheets-api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # Redirect to Netlify Functions
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Environment variables (set via Netlify UI instead!)
[build.environment]
  NODE_VERSION = "18"  # Example Node.js version

